# This skips any bundle install, which Travis will try to do because it sees a Gemfile
install: true

# This generates thumbnails in each _pages/BRANCH/images/fixedwidth
script:
  - find _pages -name "images" -exec ./mk_fixedwidth.sh {} \;

# And this deploys any generated files back to Github
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
  keep-history: true
  on:
    branch: master