# This skips any bundle install, which Travis will try to do because it sees a Gemfile
install: true

addons:
  apt:
    update: true

before_install:
  - sudo apt-get install -y yamllint

# This checks the syntax of the site and sends any errors to committer
script:
  - ./check-syntax.sh

notifications:
  email:
    on_success: never
    on_failure: always